### ISSUE TITLE
youbot_behavior_tree_editor crashes when trying to load youbot_example_BT.xml

### ISSUE THREAD

**Issue by jpwco** [BTIRAI/youbot#1]
Following the tutorial on [https://btirai.github.io/youbot](https://btirai.github.io/youbot)

running Ubuntu 18.04,
run  **youbot_behavior_tree_editor**
click menu: **File > Load**
select: **youbot_example_BT.xml**

**youbot_behavior_tree_editor** halts with the following error:

```
terminate called after throwing an instance of 'std::logic_error'
  what():  No registered model with name MoveCloseToObject
Aborted
```

Changing _MoveCloseToObject_ to _MoveCloseTo_ in youbot_example_BT.xml fixes the problem.

**Comment by miccol** [comment]
Fixes by #2 
Thank you for reporting this and the fix!
